name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  flavor:
    description: 'The Microstack LXC Ubuntu flavor, e.g. 24.04'
    required: false
    default: '24.04'
  cores:
    description: 'Amount of CPU cores to allocate to MicroStack LXC VM'
    required: false
    default: '6'
  memory:
    description: 'Amount of memory to allocate to MicroStack LXC VM'
    required: false
    default: '32GiB'
  disk:
    description: 'Amount of memory to allocate to MicroStack LXC VM'
    required: false
    default: '50GiB'

# Define your outputs here.
# outputs:
#   time:
#     description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
